import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router' 
import { useState, useCallback, useEffect } from 'react'
import PlayersConfig from '../components/players/config'

const appName = 'Desmimificando';

export default function Home({ children, href }) {

  const [players, setPlayers] = useState([]);
  const router = useRouter();
    const style = {
      background: 'red'
    }

  const addPlayer = (player) => {
    setPlayers([ ...players, player]);
  }

  const removePlayer = (player) => {
    setPlayers(players.filter(item => item !== player));
  }

  const start = useCallback((e) => {
    e.preventDefault();

    fetch('/game', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: players
    })
    .then((res) => {
      if(res.ok) router.push('/game');
    })
  }, [])

  useEffect(() => {
    // Prefetch the dashboard page
    router.prefetch('/game')
  }, [])



  return (
    <div className={styles.container}>
      <Head>
        <title>{appName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {appName}
        </h1>
        <Link href="/" locale="pt-BR">
          Português
        </Link>
        <Link href="/" locale="en-US">
          English
        </Link>


        <div className={styles.grid}>
          <div className={styles.card}>
            <PlayersConfig 
              players={players}
              addPlayer={addPlayer}
              removePlayer={removePlayer}
             />
          </div>

          <button
          type="submit"
          onClick={() => {
            router.push({
              pathname: '/game',
              query: { gameId: 'lkdkajd' },
            })
          }}
        >
          Iniciar
        </button>

        </div>
      </main>
    </div>
  )
}