import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router' 
import {Component} from 'react'
import PlayersConfig from '../components/players/config'

const appName = 'Desmimificando';
export default class Home extends Component
{

  constructor(props) {
    super(props);
    this.state = {
      players: []
    }

    this.addPlayer = this.addPlayer.bind(this);
    this.removePlayer = this.removePlayer.bind(this);
  }

  addPlayer(player) {
    this.setState((state) => ({
      players: [...state.players, player]
    }))
  }

  removePlayer(player) {
    console.log('CHAMOE', player)
    this.setState((state) => ({
      players: state.players.filter(p => p != player)
    }))
  }

  render() {
    

    return (
      <div className={styles.container}>
        <Head>
          <title>{appName}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            {appName}
          </h1>
          <Link href="/" locale="pt-BR">
            Português
          </Link>
          <Link href="/" locale="en-US">
            English
          </Link>

          <p className={styles.description}>
            Get started by editing{' '}
            <code className={styles.code}>pages/index.js</code>
          </p>

          <div className={styles.grid}>
            <div className={styles.card}>
              <PlayersConfig 
                players={this.state.players}
                addPlayer={this.addPlayer}
                removePlayer={this.removePlayer}
               />
            </div>

            <a href="https://nextjs.org/learn" className={styles.card}>
              <h2>Temas &rarr;</h2>
              <p>Learn about Next.js in an interactive course with quizzes!</p>
            </a>
          </div>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    )
  }
}
